### ISSUE TITLE
Multi-keen-project sending all events to the same keen-project

### ISSUE THREAD

**Issue by drico** [keenlabs/KeenClient-iOS#108]
In an iOS application, using the latest version of Keen IO SDK, I am sending events to 2 different projects, P1 (collection name C1) and P2 (collection name C2).

It happens that events of C2 appear in P1 and vice versa.

To reproduce this, simply use the following code, for example in `AppDelegate.m` :

    KeenClient* keenClient1 = [[KeenClient alloc] initWithProjectId:@"<P1>" andWriteKey:@"<P1_WRITE_KEY>" andReadKey:nil];
    KeenClient* keenClient2 = [[KeenClient alloc] initWithProjectId:@"<P2>" andWriteKey:@"<P2_WRITE_KEY>" andReadKey:nil];
    
    [KeenClient enableLogging];
    [keenClient1 addEvent:@{@"key1":@"value1"} toEventCollection:@"collection_app_1" error:nil];
    [keenClient2 addEvent:@{@"key2":@"value2"} toEventCollection:@"collection_app_2" error:nil];
    
    [keenClient1 uploadWithFinishedBlock:^(void) {
        NSLog(@"finished 1");
    }];
    
    [keenClient2 uploadWithFinishedBlock:^(void) {
        NSLog(@"finished 2");
    }];

The error occures in the `addEvent` method.
If you prevent the event from being sending (like by shutting down the internet connexion), you will find that the `keenEvents.sqlite` already contains wrong projects ids. (ie P1 instead of P2 and vice versa)

**Comment by heitortsergent** [comment]
Thanks for reporting this issue @drico! I'm taking a look into it.
