### ISSUE TITLE
Events not persisted in database

### ISSUE THREAD

**Issue by drico** [keenlabs/KeenClient-iOS#113]
Since release 28, events are not persisted in the SQLite database.

To reproduce, juste run the simulator and send events while having no internet connexion.

Then open keenEvents.sqlite and see there's no row in it.

**Comment by drico** [comment]
Edit : This bug does not come from release 28, it already existed before.
I know there was no bug in 83e55ed2b8d7392bb3188beca84243433bfae300
I assume this bug was introduced when adding database versionning.

**Comment by tbarn** [comment]
hey @drico! just heads up, we are working on getting this fixed now.

**Comment by heitortsergent** [comment]
@drico I'm taking a look into this, and you're absolutely right. It stops working after the commit you referred to. 

I'm gonna try to have a fix in place soon. :dancer:

**Comment by heitortsergent** [comment]
@drico I believe I fixed the issue with the commit referenced above. I'm looking into the tests now to figure out why they were not throwing any errors

**Comment by drico** [comment]
@heitortsergent I'm glad to hear it !
Any idea of when it will be released ?
