### ISSUE TITLE
Link to download SDK not updated

### ISSUE THREAD

**Issue by drico** [keenlabs/KeenClient-iOS#117]
Hi team, 
It seems that the file at the following address : "http://keen.io/static/code/KeenClient.zip" has not been updated with version 3.4.2 of the SDK (still 3.4.1).
(To be clear, this link is the one pointed by the documentation of the project.)

Could you please fix this ?

Thanks !

**Comment by terryhorner** [comment]
Sorry about that @drico! Binary files have been updated.
