### ISSUE TITLE
Crash on startup with corrupt database

### ISSUE THREAD

**Issue by Muesly** [keenlabs/KeenClient-iOS#121]
I have an app that is failing for the following reason.

In sharedClientWithProjectID it reaches createTable and fails to run the SQL due to the error "database disk image is malformed".  How the database got into this state I don't know, but in my experience it is always a possibility.

It closes the DB and proceeds, but when adding my first event, the convertNSDateToISO8601 function returns iso8601 which is nil.  The result is handleInvalidJSONInObject puts in a nil value for the timestamp dictionary field which causes a crash.

Could something be put in place to regenerate the database if malformed?

**Comment by heitortsergent** [comment]
Hi @Muesly ! Sorry for the delay in getting back to you here, and about the error.

Did you have any ideas on how we could implement this? I'm doing a little bit research, but have come empty with a way to do this directly from the library.

**Comment by Muesly** [comment]
This hasn't happened again which is good, but in my view it's always possible and maybe outside your control.  

I think you're right you need to erase the database then recreate, because it's not going to be rectifiable.  If it still fails (i.e. if openAndInitDB cannot succeed) then maybe it's best if the library stops functioning rather than crashing the whole app later down the line.
