### ISSUE TITLE
MultiAnalysis Queries can't have per-analysis Timeframes

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-iOS#127]
I'm not sure if this is just a bug in the documentation, or if there is specific code that handles/allows this, but we do *not* support timeframes on a specific analysis of a multi-analysis query. The timeframe has to be on the root request, and applies to all analyses.

FWIW, this was a bug in our API Reference, which is likely what caused the misunderstanding here. The docs are fixed now, so we just need to make sure our SDKs are in line.

**Comment by terryhorner** [comment]
This was fixed in #126.

**Comment by josephwegner** [comment]
Cool, just a docs issue then: https://github.com/keenlabs/KeenClient-iOS#multi-analysis-example

**Comment by heitortsergent** [comment]
@josephwegner when running multi-analysis queries, the SDK loops through all the queries and removes those properties (timeframe, filters, etc) from them and adds them to the root request.
