### ISSUE TITLE
multiAnalysisDictionary conversion/comparison doesn't account for arrays/objects

### ISSUE THREAD

**Issue by terryhorner** [keenlabs/KeenClient-iOS#128]
Query properties are converted to strings on line [1126](https://github.com/keenlabs/KeenClient-iOS/blob/8ceae6d5b1baf7840eb61249947a508db177fc72/KeenClient/KeenClient.m#L1126), but `filters` and `timeframe` can both be values other than a string. `filters` is an array, while `timeframe` can contain a string or an absolute timeframe that specifies `start` and `end` properties.

Both the conversion and comparison of these particular query properties need to be tweaked to handle valid values.

**Comment by huguesbr** [comment]
:+1: 

There not really converted to string but just interpreted as such.

it should be 

https://github.com/keenlabs/KeenClient-iOS/blob/8ceae6d5b1baf7840eb61249947a508db177fc72/KeenClient/KeenClient.m#L1126
```
id queryProperty = [[query propertiesDictionary] objectForKey:key];
```

https://github.com/keenlabs/KeenClient-iOS/blob/8ceae6d5b1baf7840eb61249947a508db177fc72/KeenClient/KeenClient.m#L1130
```
                } else if (![[multiAnalysisDictionary    objectForKey:key] isEqual:queryProperty]) {
```

```

**Comment by heitortsergent** [comment]
You're both right, completely missed the mark here. Gonna work on a fix tonight :full_moon_with_face:
