### ISSUE TITLE
Turn off location tracking?

### ISSUE THREAD

**Issue by PaperDot** [keenlabs/KeenClient-iOS#154]
Is there a way to disable location tracking if we don't want events to be geo-tagged? Thanks.

**Comment by terryhorner** [comment]
Indeed there is. You can call the ```disableGeoLocation``` method to disable location tracking.

https://github.com/keenlabs/KeenClient-iOS/blob/334b8cbc40a5d009439dc7e6b4fbac68aebe8bc1/KeenClient/KeenClient.m#L224

**Comment by PaperDot** [comment]
Great, thanks.
