### ISSUE TITLE
IPv6 compatibility for App Store

### ISSUE THREAD

**Issue by Muesly** [keenlabs/KeenClient-iOS#162]
I'm currently reading up on this https://developer.apple.com/news/?id=05042016a and it seems any app using various legacy IPv4 network calls will be rejected, as of at the start of this month.  

I worry whether the calls KIOreachabilityForInternetConnection & KIOreachabilityForLocalWiFi in the Keen library will cause issues?  I haven't fully investigated everything else, there maybe other calls that need looking at.

**Comment by Muesly** [comment]
May need to change + (instancetype)KIOreachabilityWithAddress:(const struct sockaddr_in *)hostAddress

to

+ (instancetype)KIOreachabilityWithAddress:(const void *)hostAddress

as sockaddr_in is a deprecated structure.

**Comment by heitortsergent** [comment]
@Muesly thanks for opening this issue. I was just doing some research on it, and it seems that the current Reachability code supports IPv6.

You can check out Apple's official Reachability code, and they have a specific section in the README about IPv6 support [here](https://developer.apple.com/library/content/samplecode/Reachability/Listings/ReadMe_md.html#//apple_ref/doc/uid/DTS40007324-ReadMe_md-DontLinkElementID_11).
