### ISSUE TITLE
Failure to open DB when formatting isoDateString returns nil, which crashes app

### ISSUE THREAD

**Issue by rist** [keenlabs/KeenClient-iOS#165]
If opening the db in ``- (id)convertNSDateToISO8601:(id)date`` fails nil is returned.
So ``- (id)convertNSDateToISO8601:(id)date`` can return nil and therefore also ``- (id)handleInvalidJSONInObject:(id)value`` could return nil.
But in line 594 of KeenClient.m you don't check if the returned value is nil and therefore try to add a nil value to the dictionary which crashes the app

**Comment by heitortsergent** [comment]
@rist thanks for opening the issue! 👍  I'll take a look at it later today and get back to you as soon as possible.
