### ISSUE TITLE
Add user-agent to requests to track SDK usage

### ISSUE THREAD

**Issue by heitortsergent** [keenlabs/KeenClient-iOS#173]
This is a suggestion of something we can do track SDK usage. We made this change at SendGrid, and the header looked like this:

`sendgrid/{sdk_version};{language}`

**Comment by josephwegner** [comment]
Love the idea here. We're discussing this internally, and want to roll it out to all of our SDKs. I'm gonna close this issue for now, though, as we haven't landed solidly on a plan.
