### ISSUE TITLE
sqlite3 library doesn't compile against iOS10.0 on Swift 2.3

### ISSUE THREAD

**Issue by charlesmastin** [keenlabs/KeenClient-iOS#174]
Upon updating my project to iOS10 I am getting some complaints with the sqlite adaptor in client 3.5.6. I get the same error after selecting "allow non-modular Includes" within Xcode.

./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:20:10: Include of non-modular header inside framework module 'KeenClient'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:35:31: Unknown type name 'sqlite3_context'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:36:27: Unknown type name 'sqlite3_context'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:37:21: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:38:23: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:39:20: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:40:22: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:41:21: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:42:32: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:43:32: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:44:39: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:45:21: Unknown type name 'sqlite3_stmt'
./Pods/KeenClient/Library/sqlite-amalgamation/keen_io_sqlite3ext.h:46:23: Unknown type name 'sqlite3_stmt'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8290:3: Unknown type name 'sqlite3_context'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8292:3: Unknown type name 'sqlite3_value'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8521:34: Unknown type name 'sqlite3_int64'; did you mean 'sqlite_int64'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8522:51: Unknown type name 'sqlite3_int64'; did you mean 'sqlite_int64'?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8536:3: Type name requires a specifier or qualifier
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk/usr/include/sqlite3.h:8536:17: Function cannot return function type 'int (Fts5Context *)' (aka 'int (struct Fts5Context *)')

**Comment by charlesmastin** [comment]
This had to do with cocoapods 0.39 and Xcode 8. Removing cocoapods, installing 1.1.0.rc.2 (as recommended in their docs), and generating fresh pods solved things.

**Comment by heitortsergent** [comment]
@charlesmastin I'm glad you got it fixed, and thanks for updating the title :shipit:

**Comment by charlesmastin** [comment]
No problem. Hopefully someone else can save some time with this gotcha.
