### ISSUE TITLE
Swift 2.3 Support - Non-Modular header error in keen_io_sqlite3ext

### ISSUE THREAD

**Issue by blakiseskream** [keenlabs/KeenClient-iOS#178]
Hello,

We recently upgraded to Swift 2.3 in Xcode 8.0 and have been having package errors with Keen in order to get it to compile. Specifically in keen_io_sqlite3ext.h the following code at line 20 is giving an error

`#include "sqlite3.h"`

Error description is `Include of non-modular header inside framework module KeenClient`

This is cascading errors down to the struct below and other Keen sqlite files creating type errors on the sqllite3 types.

Any info on how to remedy this issue would be helpful! Let me know if you need anymore information from me. Haven't had any issues with the client until we upgraded to 2.3 / Xcode 8. App and other packages run great when KeenClient is removed from app.

Thanks!

**Comment by heitortsergent** [comment]
Hi @blakiseskream! I'm sorry you're seeing this error. :(

How are you importing the SDK into your project?

**Comment by blakiseskream** [comment]
Hello,

We are using pods. Podfile includes build setting for Swift 2.3. We are not forcing any particular version of Keen.

**Comment by heitortsergent** [comment]
Thanks @blakiseskream, I'm going to try to reproduce the issue.

In the meantime, did you try any of the fixes on this [SO link](http://stackoverflow.com/questions/24103169/swift-compiler-error-non-modular-header-inside-framework-module)?

**Comment by blakiseskream** [comment]
Hi @heitortsergent ,

I tried the answers in that SO link as well as the ones in [this](http://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module) SO post. 

To clarify the remedies I attempted are,
1) Adding Header to Public in side panel
2) Going to Pods.xcodeproj -> KeenClient -> Headers -> Adding keen_io_sqllite3.h and keen_io_sqllite3ext.h to Public
3) Pods.xcodeproj -> Build Settings -> Allow Non-modular includes in Framework Modules to 'YES'
4) Adding `            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'` to podfile.

After all of these changes I am still getting the same error.

**Comment by heitortsergent** [comment]
Ok, thanks @blakiseskream! I'm looking into it, I'll let you know as soon as I find a fix.

**Comment by heitortsergent** [comment]
@blakiseskream this might be an issue with CocoaPods. What version of it are you using? If you're not using the latest version (v1.1.1), could you please try upgrading?

And then doing a thorough cleanup is also a good idea:

1. Clean Build -> ⇧⌘K (Shift + Command + K) - to clean builded frameworks.
2. Clean Build Folder -> ⌥⇧⌘K (Option+Shift+Command+K)
3. Close Xcode
4. $ rm -rf ~/Library/Developer/Xcode/DerivedData
5. $ pod update
6. Open Xcode and build

Please let me know if this works. 💃

**Comment by blakiseskream** [comment]
This worked great!

My pods wasn't updated. After updating to 1.1.1 and going through the cleaning and updating process it worked great!

**Comment by heitortsergent** [comment]
That's great @blakiseskream! 🎉 

Let us know if you run into any other issues.
