### ISSUE TITLE
Add support for Saved & Cached Queries

### ISSUE THREAD

**Issue by josephwegner** [keenlabs/KeenClient-iOS#181]
## MVP
- [x] Retrieve Results from Saved Query

## Intentionally left out of iOS SDK
- Create Saved Query
- Cache a Saved Query
- Uncache a Saved Query
- Delete a Saved Query
- Retrieve definition of a saved query
- Update a cached query

**Comment by baumatron** [comment]
According to API documentation, much of what's listed here requires a master key (creation, caching, deleting). There isn't currently a notion of master keys in the iOS SDK, just read and write keys (which of course could be master keys). Implementing those features would require introducing that notion.

**Comment by baumatron** [comment]
Updated MVP to reflect that we don't want to worry about features that require master keys in a client SDK.

**Comment by baumatron** [comment]
Merged to vnext_minor so will go into the next minor release.
