### ISSUE TITLE
Fresh install: `error: 'KeenLogger.h' file not found`

### ISSUE THREAD

**Issue by capnslipp** [keenlabs/KeenClient-iOS#216]
I'm trying out integrating keen.io for a iOS Swift/Obj-C project.  First time keen.io customer; no other analytics currently being used in my in-development app.

I followed the Carthage + Swift Installation instructions; carthage's build ran fine, and I added `KeenClient.framework` to my project's Embedded Binaries and added the import to my bridging header.

I'm getting the following errors when I build my project:

~~~
…/MyProject/App/MyProject-Bridging-Header.h:10:9: note: while building module 'KeenClient' imported from …/MyProject/App/MyProject-Bridging-Header.h:10:
#import <KeenClient/KeenClient.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/KeenClientFramework.h"
        ^
…/MyProject/Carthage/Build/iOS/KeenClient.framework/Headers/KeenClientFramework.h:19:9: note: in file included from …/MyProject/Carthage/Build/iOS/KeenClient.framework/Headers/KeenClientFramework.h:19:
#import <KeenClient/KeenClient.h>
        ^
…/MyProject/Carthage/Build/iOS/KeenClient.framework/Headers/KeenClient.h:14:9: error: 'KeenLogger.h' file not found
#import "KeenLogger.h"
        ^
…/MyProject/App/MyProject-Bridging-Header.h:10:9: error: could not build module 'KeenClient'
#import <KeenClient/KeenClient.h>
        ^
<unknown>:0: error: failed to import bridging header '…/MyProject/App/MyProject-Bridging-Header.h'
~~~

The issue seems to be that the `KeenClient.framework` has public headers `HTTPCodes.h`, `KeenClient.h`, `KeenClientFramework.h`, `KeenProperies.h`, `KIODBStore.h`, `KIOQuery.h`, & `KIOReachability.h`, __but no header with the name `KeenLogger.h`__.

The version of KeenClient-iOS that carthage installed was 3.6.0.

Cheers.

**Comment by baumatron** [comment]
The fix for this should now be available in 3.6.1.
