### ISSUE TITLE
I'll do the request for Location Permissions, thank you

### ISSUE THREAD

**Issue by knightcode** [keenlabs/KeenClient-iOS#77]
A call to sharedClientWithProjectId will prompt the user for access to location services if he or she hasn't previously been prompted. Since that's not the first thing we want our users to see, I don't think I can start using this client until AFTER our onboarding experience is complete. That's one big funnel we can't track.

**Comment by dkador** [comment]
I'm mobile so I can't find the docs right now but you can disable our SDK's use of location services right when the app starts (make it your first reference to KeenClient). 




Then you can control asking your users for that and re-enable it in the SDK whenever you want to.




Hope that helps!

**Comment by knightcode** [comment]
That did help. thanks.
