### ISSUE TITLE
Crash in keen_io_sqlite3_clear_bindings

### ISSUE THREAD

**Issue by underscoretang** [keenlabs/KeenClient-iOS#79]
@terryhorner 

We're getting EXC_BAD_ACCESS crashes in keen_io_sqlite3.c:65858

pStmt is NULL in this situation

It's being called from KIOEventStore.m:515

keen_io_sqlite3_bind_text(convert_date_stmt, 1, [[NSString stringWithFormat:@"%f", [date timeIntervalSince1970]] UTF8String], -1, SQLITE_STATIC) 

is returning 21

**Comment by terryhorner** [comment]
@underscoretang we're working on tackling this. 

Do you happen to have any additional information as to the data that's being passed in those situations (os version, device, language, etc)?

**Comment by tylrtrmbl** [comment]
Can this be closed?

**Comment by underscoretang** [comment]
yup
