### ISSUE TITLE
getPendingEventCount returns wrong value unless getEvents is called first.

### ISSUE THREAD

**Issue by timseries** [keenlabs/KeenClient-iOS#96]
[[KeenClient getEventStore] getPendingEventCount] returns nil or a stale value unless [[KeenClient getEventStore] getEvents] is called first. I assume the KIOEventStore object is a singleton here. But even if I store a reference to one instance of KIOEventStore the same behavior occurs.

**Comment by heitortsergent** [comment]
@timseries looking into this, thanks for reporting. :D

Just to be sure, are you running version 3.3.0?

**Comment by timseries** [comment]
Sorry, I assumed we were running the most up to date version. We're actually running 3.2.20. I am happy to close this issue and re-raise if necessary after upgrade.

**Comment by heitortsergent** [comment]
No worries @timseries, thanks for checking. I'll try to reproduce this as well just in case. Would the steps be:

1. Start a new instance of KeenClient
2. Call `addEvent`
3. Call `getPendingEventCount`
