### ISSUE TITLE
Reachability in Podspec

### ISSUE THREAD

**Issue by benpious** [keenlabs/KeenClient-iOS#97]
Reachability is included as source files (Reachability.m and .h) in the podspec of KeenClient, however, Reachability is itself a Cocoapod which other pods such as AWSCore rely on. Attempting to use KeenClient with these pods will cause the build to fail, citing "duplicated symbols for architecture arm64."

**Comment by claireyoung** [comment]
Thanks Ben! I just wanted to verify that I was able to easily reproduce this by just adding AWSCore to my project. As you mentioned, I am getting a duplicate symbol linker error for Reachability.

**Comment by tylrtrmbl** [comment]
The correct solution for Cocoapods is to list Reachability as a dependent Pod. Yes, we have a linker error as well.
